name: post_frame
description: A Flutter package that provides utilities for executing actions after the current frame has been rendered, with support for waiting on scroll controllers and layout metrics.
issue_tracker: https://github.com/SoundSliced/post_frame/issues
repository: https://github.com/SoundSliced/post_frame
version: 2.0.2
homepage: https://github.com/SoundSliced/post_frame

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  s_packages: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
